### ISSUE TITLE
Root font-size?

### ISSUE THREAD

**Issue by ryanmclaughlin** [aurora-kit/aurora-grid#2]
Re-defining the root `font-size` is probably not the best idea, especially not even allowing it as a setting.  Is there a better solution for this need? 

I'd almost say the same for the `box-sizing`, but I'm sure that's a requirement for flexbox.

**Comment by elrumordelaluz** [comment]
@ryanmclaughlin since it remained this declaration without any special scope, just updated in the [last commit](https://github.com/aurora-kit/aurora-grid/commit/06584b8b10e49ed5b3d902d665575d66db601ae5). The `$ae-font-size` variable remains available in `aurora-shared` anyway.

**Comment by ryanmclaughlin** [comment]
:+1:
