### ISSUE TITLE
Aspect ratio for bg images

### ISSUE THREAD

**Issue by fluxxus** [aurora-kit/aurora-grid#3]
This is really not an issue, nor it is related to Aurora grid, but didn't knew where to ask so here it is.

In your Urku theme I saw a very interesting approach to maintaining aspect ratios for bg images. What is the reasoning behind the `padding-top` values used there? Is it from this article http://nicolasgallagher.com/flexible-css-cover-images/ ?  The values used there are different though.

p.s. One suggestion. Add an Image Portfolio repo to github, it is brilliant. All the possibilities+ switch options are truly amazing. It could be like an add-on for Aurora grid. And thanks for the grid, I've switched to it for my latest project,  really nice work !

**Comment by elrumordelaluz** [comment]
@Madebym for Urku Portfolio we used four `aspect-ratios` based on the [original](http://www.pixeden.com/psd-web-templates/urku-portfolio-psd-website) desgin. There are `landscape`, `landscape-alt`, `portrait` and `square` as default. The idea and principle is the same as the one mention in the article, we use a calculation that comes from a simple Sass function that `returns ( $h / ($w / 100) ) * 1%`. You could use your own if you want, creating an class that overrides the `padding-top` on the pseudo-element.

The idea to create a repo for the template is on the list. We really appreciate you like it.

**Comment by fluxxus** [comment]
Ok, thanks for the clarification !
