### ISSUE TITLE
Weird wrapping of columns

### ISSUE THREAD

**Issue by fluxxus** [aurora-kit/aurora-grid#4]
Not sure if this has something with  `flex-wrap:wrap` on the grid container, or some other property, but I am having a very weird column wrap case. 

Here is the fiddle https://jsfiddle.net/LmLo4x69/ . It is completely broken in Firefox, and works to some extent in Chrome.

The columns begin wrapping(stacking) before the xs layout kicks in.

Here is the same thing with flexbox grid. https://jsfiddle.net/16dwj7k0/

In this fiddle the columns wrap exactly when the xs layout starts. I think that something is broken in how Aurora grid behaves.

Guess it is something with flex shorthand on each ae-grid__item, and not related to flex-wrap on the container.

Please correct me if I am wrong.

**Comment by elrumordelaluz** [comment]
Hi @Madebym, first of all huge thanks for the catch. It seems that there were a missing `max-width`, solved [here](https://github.com/aurora-kit/aurora-grid/releases/tag/v1.0.5). 

The `flex-wrap: wrap` is a desired behaviour to do things like this
![aurora](https://cloud.githubusercontent.com/assets/784056/13059610/b1d68b6e-d42b-11e5-8e97-0777d8648449.gif)

[Here](https://jsfiddle.net/dngesLdL/) is the fiddle forked with the last version of Aurora. Please let us know if this works for you.

**Comment by fluxxus** [comment]
@elrumordelaluz  Yes, the grid behaves as expected with the last version of Aurora. Glad that I could help by catching the bug.

**Comment by elrumordelaluz** [comment]
:+1: thanks  again @Madebym
