### ISSUE TITLE
Error: Undefined variable: "$min-val"

### ISSUE THREAD

**Issue by daveranan** [aurora-kit/aurora-grid#5]
When you install project as is and run $ gulp command, error prevents it from being built:

```
Error: src/_functions.scss
Error: Undefined variable: "$min-val".
        on line 101 of src/_functions.scss
>>   $min-query: if($min-val and $min-val != 0, '(min-width: #{$min-val})', null)
   -----------------^
```

Of course, I ran `npm install` first but apparently, some variables are missing out.

**Comment by elrumordelaluz** [comment]
Hi @daveranan, thank you for report the issue, should be solved in `1.0.7`. 
Let us know.
